// This file is automatically generated
#ifndef OUTPUT_LAYER_4_H_
#define OUTPUT_LAYER_4_H_
#include <stdint.h>
 int8_t __attribute__((section(".xheep_data_interleaved"))) output_layer_4[] = {
18,0,0,0,0,115,0,0,
};

#endif //OUTPUT_LAYER_4_H_
