#!/usr/bin/env bash
# Copyright EPFL contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# Runs Vitis HLS synthesis for the dot_product engine, copies the generated
# RTL into rtl/hls/, and (re)generates dot_product.core listing it -- so
# `make verilator-build` / `make vivado-fpga` can pick it up via FuseSoC.
#
# Usage:
#   source <vivado_install>/settings64.sh
#   source <vitis_hls_install>/settings64.sh
#   ./generate_core.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

if ! command -v vitis_hls >/dev/null 2>&1; then
  echo "error: vitis_hls not found in PATH -- source Vivado's and Vitis HLS's settings64.sh first" >&2
  exit 1
fi

rm -rf dot_product_proj
vitis_hls -f run_hls.tcl

SYN_DIR="dot_product_proj/solution1/syn/verilog"
DST_DIR="rtl/hls"

if [ ! -d "$SYN_DIR" ]; then
  echo "error: HLS synthesis did not produce $SYN_DIR -- check hls_run.log" >&2
  exit 1
fi

mkdir -p "$DST_DIR"
rm -f "$DST_DIR"/*.v
cp "$SYN_DIR"/*.v "$DST_DIR"/

# Strip the per-file `timescale directive Vitis HLS emits: no other file in
# this project sets one (X-HEEP relies on Verilator's single implicit
# timescale), so leaving it in would make every other module in the whole
# design "inconsistent" in Verilator 5's eyes (TIMESCALEMOD warning) rather
# than just these few files.
sed -i '/^`timescale /d' "$DST_DIR"/*.v

HLS_FILES=$(cd "$DST_DIR" && ls *.v | sort | sed 's/^/    - rtl\/hls\//')

cat >dot_product.core <<EOF
CAPI=2:

# Auto-generated by generate_core.sh -- do not edit by hand.
# Regenerate with:
#   source <vivado_install>/settings64.sh && source <vitis_hls_install>/settings64.sh
#   ./generate_core.sh

name: "epfl:ip:dot_product"
description: "HLS-generated streaming dot-product accelerator, wrapped for X-HEEP OBI."

filesets:
  files_rtl:
    depend:
    - x-heep::packages
    - pulp-platform.org::obi
    - pulp-platform.org::axi
    - pulp-platform.org::axi_obi
    - x-heep:ip:xheep_obi_to_axi_bridge
    - x-heep:ip:xheep_axi_to_obi_bridge
    files:
$HLS_FILES
    - rtl/dot_product_xheep_wrapper.sv
    file_type: systemVerilogSource

  verilator-waiver:
    files:
    - dot_product.vlt
    file_type: vlt

targets:
  default:
    filesets:
    - files_rtl
    - tool_verilator ? (verilator-waiver)
EOF

n_files=$(echo "$HLS_FILES" | wc -l)
echo "Generated dot_product.core: ${n_files} HLS RTL file(s) + wrapper, from ${SYN_DIR}."
